version: '3'
services:
    rc_timeh:
        build: ./
        ports:
            - 127.0.0.1:25065:80
        environment:
            - FPM_PM_MAX_CHILDREN=32
    mysql:
        build: ./mysql
        volumes:
            - mysqlvol2:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: p4s3ca
            MYSQL_DATABASE: paseca
volumes:
    mysqlvol2:
