version: '3.3'

services:
  task-totp:
    build: .
    environment:
      - WEB_CONCURRENCY=4
    ports:
        - "127.0.0.1:25003:80"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
