version: "3.3"

services:
  service:
    build: .
    restart: on-failure
    read_only: true
    shm_size: 16
    networks:
        - no-internet
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          cpus: '0.4'
          memory: 256m
    ulimits:
      nproc: 128
      nofile:
        soft: 128
        hard: 128
    tmpfs:
      - /tmp

  haproxy:
    build: ./haproxy
    restart: on-failure
    ports:
        - 25081:1337
    networks:
        - no-internet
        - internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
