version: '3'
services:
  subway:
    build: ./
    ports:
        - 127.0.0.1:25080:1337
    restart: always
    volumes:
        - taskdata:/var/subway
        - tasks:/etc/subway/tasks

volumes:
    taskdata:
    tasks:
