version: '3'
services:
    idor_of:
        build: ./
        ports:
            - 127.0.0.1:25041:80
        deploy:
          resources:
            limits:
              cpus: '0.4'
              memory: 64M
        depends_on:
            - mysql
    mysql:
        build: ./mysql
        volumes:
            - mysqlvol:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: p4s3c4
            MYSQL_DATABASE: paseca
        deploy:
          resources:
            limits:
              cpus: '0.4'
              memory: 256M
volumes:
    mysqlvol:
